### ISSUE TITLE
Request for ownership transfer of this crate to rust-embedded-community

### ISSUE THREAD

**Issue by sourcebox** [rust-embedded-community/usbd-midi#14]
Background: [rust-embedded-community](https://github.com/orgs/rust-embedded-community/repositories) maintains the `usb-device` crate as well as some class implementations like `usbd-serial`. 

As this crate isn't actively maintained (last release was years ago), it doesn't use the latest version of `usb-device`, leading to a version conflict with HALs and other class implementations. Transferring this crate would improve the situation by having the chance to keep the versions in sync as well as implementing new features by the community. 

The suggestion for this request was made by some member of `rust-embedded-community`.

**Comment by btrepp** [comment]
@x37v I believe was interested in transferring it to rust midi.

I am fine either way. Happy to have it folded under either org

**Comment by thejpster** [comment]
Happy to have it in github.com/rust-embedded-community. I believe the instructions are in https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository

**Comment by btrepp** [comment]
> Happy to have it in github.com/rust-embedded-community. I believe the instructions are in https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository

`To transfer a repository that you own to an organization, you must have permission to create a repository in the target organization.`

for the crate. @x37v has ownership from the other gh issue on this. So, I can't transfer it. x37v I have noticed you never pushed a new release, are you happy to have it transferred to the embedded group?

**Comment by x37v** [comment]
> For the crate. @x37v has ownership from the other gh issue on this. So, I can't transfer it. x37v I have noticed you never pushed a new release, are you happy to have it transferred to the embedded group?

I didn't think you ever gave us access to the crate but also we ended up with some bugs that we haven't yet fixed.
I think it makes sense to transfer it to the embedded community, especially if they're going to be more active maintaining it. I can always bring up my hopes/dreams for the crate with them.

**Comment by btrepp** [comment]
@x37v I think this was transferred to yourself a while back, I no longer can transfer to others.

![image](https://github.com/btrepp/usbd-midi/assets/262933/741a764f-3274-4452-b350-83fb300dc658)

**Comment by sourcebox** [comment]
In that case @x37v would have to add the rust-embedded-community as owner via the cargo command shown above. Btw. anyone of you can still have full access to the crate, there is no need to remove the permissions after transferring. It's mostly that more people can work on it.

**Comment by sourcebox** [comment]
There's now a document from embedded-rust-community that describes the transfer process in detail:
https://github.com/rust-embedded-community/meta/blob/master/TRANSFER.md

**Comment by btrepp** [comment]
> In that case @x37v would have to add the rust-embedded-community as owner via the cargo command shown above. Btw. anyone of you can still have full access to the crate, there is no need to remove the permissions after transferring. It's mostly that more people can work on it.

I believe the cargo team before asked if I was happy to xfer it, so it was done via email. I imagine they removed me

> There's now a document from embedded-rust-community that describes the transfer process in detail: https://github.com/rust-embedded-community/meta/blob/master/TRANSFER.md

I think I followed the second path without joining, assuming @sourcebox was part of the rust embedded community, so I think the transfer is to you first?, then you can put it in the organization. This seems like it might be quicker than waiting for someone to add me there. Hopefully that helps.

**Comment by sourcebox** [comment]
Thanks for initiating the transfer, I will pass over the repository to the organization.

@x37v : Can you please add me or the organization as owner on crates.io? You are the only one who can do it as you are the sole owner there.

**Comment by x37v** [comment]
@sourcebox I just sent you an invite via crates.io

**Comment by sourcebox** [comment]
> @sourcebox I just sent you an invite via crates.io

Thanks, I've accepted it and was added as an owner. I'm currently doing some basic cleanup on the code and will then pass it over to the group.

**Comment by sourcebox** [comment]
The transfer is now complete and permissions for the group are also setup on crates.io. Thanks to everybody for making it possible!
