### ISSUE TITLE
version bump and release?

### ISSUE THREAD

**Issue by x37v** [rust-embedded-community/usbd-midi#9]
Is the code as is stable enough for a new release? I see that crates.io has `usbd-midi 0.2.0` but that version doesn't have the midi read support that is in the main branch here..

**Comment by btrepp** [comment]
I haven't really tested the community contributions. So mileage may vary
for 'stable' in a non production version.

I believe most people are using it from git.

That being said, I am happy to release a new version of it helps. The
changes shouldn't really be all that incompatible.

**Comment by x37v** [comment]
I'm able to use it from git too but was initially a little confused when the example on the front page didn't work with what I had installed via `crates.io` .. not uncommon with rust projects, nice that it is so easy.

**Comment by btrepp** [comment]
Ah yeah I guess some of the prs didn't update the doc.

Honestly I am not super actively developing this. It was used in a device
that is completed, which I don't need new firmware for, but I am happy to
maintain and help others.

In regards to the example. If you could update it a PR that would be great.
From there I will publish it to crates to help any other newcomers.

**Comment by x37v** [comment]
> Honestly I am not super actively developing this. It was used in a device that is completed, which I don't need new firmware for, but I am happy to maintain and help others.

Hey @btrepp .. I am willing/interested to take this crate over and migrate it over to https://github.com/rust-midi/

I have a PR #11 up here that integrates the shared midi type/conversion code that @mendelt and I have been collaborating on and also have a re-org/simplification staged that I believe addresses the concerns of the previous #10 draft request. If you want to take a look at #11 I'd be happy for that but if you're just wanting to hand off the project I'd fork it over to `rust-midi` (and ideally get crates.io access for `usbd-midi` eventually).

**Comment by btrepp** [comment]
I've had a look at #11 and am happy with it, just have a suggestion for the breaking change aspect and it's good to go.

I'm happy for it to be moved into rust-midi. It's logical to sit inside a broader ecosystem, and will make it easier to use and align the types.

I've added you as a collaborator to this repo to help facilitate this.

**Comment by sourcebox** [comment]
Version 0.3.0 was just released on crates.io.
